#!/usr/bin/env sh
set -eu

REPO="${XTUNNEL_REPO:-6Kmfi6HP/x-tunnel}"
VERSION="${XTUNNEL_VERSION:-latest}"
MODE="${XTUNNEL_MODE:-cloudflared}"
LISTEN_HOST="${XTUNNEL_LISTEN_HOST:-}"
LISTEN_PORT="${XTUNNEL_LISTEN_PORT:-18080}"
TUNNEL_PATH="${XTUNNEL_PATH:-/tunnel}"
TOKEN="${XTUNNEL_TOKEN:-}"
METRICS="${XTUNNEL_METRICS:-127.0.0.1:18081}"
UPSTREAM_SOCKS5="${XTUNNEL_UPSTREAM_SOCKS5:-}"
CIDR="${XTUNNEL_CIDR:-0.0.0.0/0,::/0}"
ALLOW_TARGET="${XTUNNEL_ALLOW_TARGET:-}"
DENY_TARGET="${XTUNNEL_DENY_TARGET:-}"
ALLOW_HOST="${XTUNNEL_ALLOW_HOST:-}"
DENY_HOST="${XTUNNEL_DENY_HOST:-}"
MAX_CLIENTS="${XTUNNEL_MAX_CLIENTS:-0}"
MAX_STREAMS="${XTUNNEL_MAX_STREAMS:-0}"
INSTALL_DIR="${XTUNNEL_INSTALL_DIR:-/usr/local/bin}"
CONFIG_DIR="${XTUNNEL_CONFIG_DIR:-/etc/x-tunnel}"
SERVICE_NAME="${XTUNNEL_SERVICE_NAME:-x-tunnel}"
BINARY_URL="${XTUNNEL_BINARY_URL:-}"
PUBLIC_HOST="${XTUNNEL_PUBLIC_HOST:-}"
CLOUDFLARED_URL="${XTUNNEL_CLOUDFLARED_URL:-}"
CLIENT_LISTEN="${XTUNNEL_CLIENT_LISTEN:-socks5://127.0.0.1:11080,http://127.0.0.1:11081}"
CLIENT_CONNECTIONS="${XTUNNEL_CLIENT_CONNECTIONS:-1}"
CLIENT_FALLBACK="${XTUNNEL_CLIENT_FALLBACK:-true}"
CLIENT_INSECURE="${XTUNNEL_CLIENT_INSECURE:-false}"
CLIENT_METRICS="${XTUNNEL_CLIENT_METRICS:-127.0.0.1:11082}"
NON_INTERACTIVE="${XTUNNEL_NON_INTERACTIVE:-false}"
SKIP_START="${XTUNNEL_SKIP_START:-false}"
PRINT_ONLY="${XTUNNEL_PRINT_ONLY:-false}"

usage() {
  cat <<'EOF'
x-tunnel server one-click installer

Usage:
  server.sh [options]

Modes:
  --mode cloudflared       Install x-tunnel on 127.0.0.1 and expose it with a temporary trycloudflare.com URL.
  --mode direct            Listen on 0.0.0.0 and output a ws://host:port/path client config.

Options:
  --non-interactive        Do not prompt; fail if required values cannot be generated or detected.
  --version VERSION        Release tag to install, for example v0.2.0. Default: latest.
  --binary-url URL         Download the x-tunnel binary from this URL instead of GitHub releases.
  --token TOKEN            Server/client pre-shared token. A random token is generated by default.
  --listen-port PORT       Server listen port. Default: 18080.
  --path PATH              WebSocket path. Default: /tunnel.
  --metrics HOST:PORT      Server metrics address. Default: 127.0.0.1:18081.
  --public-host HOST       Direct-mode public host/IP. Auto-detected when omitted.
  --upstream-socks5 URL    Server-side egress SOCKS5 proxy, for example socks5://user:pass@host:1080.
  --cidr CIDRS            Allowed client source CIDRs. Default: 0.0.0.0/0,::/0.
  --allow-target CIDRS     Server target allow CIDRs.
  --deny-target CIDRS      Server target deny CIDRs.
  --allow-host HOSTS       Server target allow hosts.
  --deny-host HOSTS        Server target deny hosts.
  --max-clients N          Server max client sessions. Default: 0.
  --max-streams N          Server max streams per client. Default: 0.
  --client-listen VALUE    Client listen string for generated config.
  --skip-start             Install files but do not start/restart services.
  --print-only             Print resolved config without installing.
  -h, --help               Show this help.

Environment variables mirror options with XTUNNEL_ prefixes, for example:
  XTUNNEL_MODE=direct XTUNNEL_TOKEN=... XTUNNEL_NON_INTERACTIVE=true ./server.sh
EOF
}

log() {
  printf '%s\n' "$*" >&2
}

die() {
  log "error: $*"
  exit 1
}

is_true() {
  case "$1" in
    1|true|TRUE|yes|YES|y|Y|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

json_escape() {
  awk 'BEGIN {
    s = ARGV[1]
    ARGV[1] = ""
    gsub(/\\/,"\\\\",s)
    gsub(/"/,"\\\"",s)
    gsub(/\t/,"\\t",s)
    gsub(/\r/,"\\r",s)
    gsub(/\n/,"\\n",s)
    printf "%s", s
  }' "$1"
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

as_root() {
  [ "$(id -u)" -eq 0 ] || die "run as root"
}

prompt() {
  var_name="$1"
  label="$2"
  default_value="$3"
  current_value="$(eval "printf '%s' \"\${$var_name}\"")"
  [ -n "$current_value" ] && return 0
  if is_true "$NON_INTERACTIVE"; then
    eval "$var_name=\$default_value"
    return 0
  fi
  printf '%s [%s]: ' "$label" "$default_value" >&2
  IFS= read -r answer || answer=""
  [ -n "$answer" ] || answer="$default_value"
  eval "$var_name=\$answer"
}

prompt_value() {
  var_name="$1"
  label="$2"
  default_value="$(eval "printf '%s' \"\${$var_name}\"")"
  printf '%s [%s]: ' "$label" "$default_value" >&2
  IFS= read -r answer || answer=""
  [ -n "$answer" ] || answer="$default_value"
  eval "$var_name=\$answer"
}

interactive_prompts() {
  is_true "$NON_INTERACTIVE" && return 0
  [ -t 0 ] || return 0
  [ -n "$TOKEN" ] || TOKEN="$(random_token)"
  prompt_value MODE "Expose mode (cloudflared/direct)"
  prompt_value LISTEN_PORT "Server listen port"
  prompt_value TUNNEL_PATH "WebSocket path"
  prompt_value TOKEN "Pre-shared token"
  prompt_value METRICS "Server metrics address"
  if [ "$MODE" = "direct" ]; then
    [ -n "$PUBLIC_HOST" ] || PUBLIC_HOST="$(detect_public_host 2>/dev/null || true)"
    prompt PUBLIC_HOST "Direct-mode public host/IP" "$PUBLIC_HOST"
  fi
}

random_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
  elif [ -r /dev/urandom ]; then
    od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
  else
    date +%s | awk '{printf "x-tunnel-token-%s\n", $1}'
  fi
}

detect_arch() {
  machine="$(uname -m)"
  case "$machine" in
    x86_64|amd64) printf 'amd64' ;;
    aarch64|arm64) printf 'arm64' ;;
    *) die "unsupported architecture: $machine" ;;
  esac
}

download() {
  url="$1"
  out="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$out"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$out" "$url"
  else
    die "curl or wget is required for downloads"
  fi
}

http_get() {
  url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$url"
  else
    return 1
  fi
}

latest_tag() {
  if [ "$VERSION" != "latest" ]; then
    printf '%s' "$VERSION"
    return 0
  fi
  url="https://github.com/${REPO}/releases/latest"
  if command -v curl >/dev/null 2>&1; then
    effective="$(curl -fsSLI -o /dev/null -w '%{url_effective}' "$url")" || return 1
  elif command -v wget >/dev/null 2>&1; then
    effective="$(wget -S --spider "$url" 2>&1 | awk '/^  Location: /{loc=$2} END{print loc}')" || return 1
  else
    return 1
  fi
  tag="${effective##*/}"
  [ -n "$tag" ] && [ "$tag" != "latest" ] || return 1
  printf '%s' "$tag"
}

detect_public_host() {
  for url in https://api.ipify.org https://ifconfig.me; do
    host="$(http_get "$url" 2>/dev/null | tr -d '[:space:]' || true)"
    if [ -n "$host" ]; then
      printf '%s' "$host"
      return 0
    fi
  done
  return 1
}

write_server_config() {
  file="$1"
  listen_url="$2"
  tmp="${file}.tmp"
  {
    printf '{\n'
    printf '  "listen": "%s",\n' "$(json_escape "$listen_url")"
    if [ -n "$UPSTREAM_SOCKS5" ]; then
      printf '  "forward": "%s",\n' "$(json_escape "$UPSTREAM_SOCKS5")"
    fi
    printf '  "token": "%s",\n' "$(json_escape "$TOKEN")"
    printf '  "cidr": "%s",\n' "$(json_escape "$CIDR")"
    [ -n "$ALLOW_TARGET" ] && printf '  "allow-target": "%s",\n' "$(json_escape "$ALLOW_TARGET")"
    [ -n "$DENY_TARGET" ] && printf '  "deny-target": "%s",\n' "$(json_escape "$DENY_TARGET")"
    [ -n "$ALLOW_HOST" ] && printf '  "allow-host": "%s",\n' "$(json_escape "$ALLOW_HOST")"
    [ -n "$DENY_HOST" ] && printf '  "deny-host": "%s",\n' "$(json_escape "$DENY_HOST")"
    printf '  "metrics": "%s",\n' "$(json_escape "$METRICS")"
    printf '  "max_clients": %s,\n' "$MAX_CLIENTS"
    printf '  "max_streams": %s,\n' "$MAX_STREAMS"
    printf '  "dial_timeout": "5s",\n'
    printf '  "ws_handshake_timeout": "5s",\n'
    printf '  "udp_read_timeout": "1s",\n'
    printf '  "shutdown_timeout": "10s"\n'
    printf '}\n'
  } >"$tmp"
  install -m 0600 "$tmp" "$file"
  rm -f "$tmp"
}

write_client_config() {
  forward="$1"
  include_front="$2"
  {
    printf '{\n'
    printf '  "listen": "%s",\n' "$(json_escape "$CLIENT_LISTEN")"
    printf '  "forward": "%s",\n' "$(json_escape "$forward")"
    printf '  "token": "%s",\n' "$(json_escape "$TOKEN")"
    printf '  "connections": %s,\n' "$CLIENT_CONNECTIONS"
    printf '  "fallback": %s,\n' "$CLIENT_FALLBACK"
    printf '  "insecure": %s,\n' "$CLIENT_INSECURE"
    printf '  "metrics": "%s",\n' "$(json_escape "$CLIENT_METRICS")"
    printf '  "dial_timeout": "3s",\n'
    printf '  "ws_handshake_timeout": "5s",\n'
    printf '  "reconnect_delay": "1s",\n'
    printf '  "reconnect_max_delay": "10s",\n'
    printf '  "reconnect_jitter": "250ms",\n'
    printf '  "rtt_timeout": "2s"'
    if is_true "$include_front"; then
      printf ',\n'
      printf '  "websocket_front_proxy": {\n'
      printf '    "enabled": true,\n'
      printf '    "type": "http_connect",\n'
      printf '    "server": "cloudnproxy.baidu.com:443",\n'
      printf '    "connect_host": "sptest.baidu.com",\n'
      printf '    "headers": {\n'
      printf '      "X-T5-Auth": "482857715",\n'
      printf '      "User-Agent": "okhttp/3.11.0 Dalvik/2.1.0 (Linux; Build/RKQ1.200826.002) baiduboxapp/11.0.5.12 (Baidu; P1 11)",\n'
      printf '      "Proxy-Connection": "keep-alive",\n'
      printf '      "Connection": "keep-alive"\n'
      printf '    }\n'
      printf '  }\n'
    else
      printf '\n'
    fi
    printf '}\n'
  }
}

write_systemd_service() {
  service_file="/etc/systemd/system/${SERVICE_NAME}.service"
  cat >"$service_file" <<EOF
[Unit]
Description=x-tunnel server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/x-tunnel -config ${CONFIG_DIR}/server.json
Restart=always
RestartSec=3
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF
}

install_cloudflared() {
  if command -v cloudflared >/dev/null 2>&1; then
    return 0
  fi
  arch="$(detect_arch)"
  url="${CLOUDFLARED_URL:-https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${arch}}"
  tmp="$(mktemp)"
  log "downloading cloudflared from $url"
  download "$url" "$tmp"
  install -m 0755 "$tmp" /usr/local/bin/cloudflared
  rm -f "$tmp"
}

write_cloudflared_service() {
  service_file="/etc/systemd/system/${SERVICE_NAME}-cloudflared.service"
  cat >"$service_file" <<EOF
[Unit]
Description=x-tunnel temporary Cloudflare tunnel
After=network-online.target ${SERVICE_NAME}.service
Wants=network-online.target
Requires=${SERVICE_NAME}.service

[Service]
Type=simple
ExecStart=/usr/local/bin/cloudflared tunnel --no-autoupdate --url http://127.0.0.1:${LISTEN_PORT}
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
}

start_services() {
  systemctl daemon-reload
  systemctl enable "${SERVICE_NAME}.service" >/dev/null
  systemctl restart "${SERVICE_NAME}.service"
  if [ "$MODE" = "cloudflared" ]; then
    systemctl enable "${SERVICE_NAME}-cloudflared.service" >/dev/null
    systemctl restart "${SERVICE_NAME}-cloudflared.service"
  elif [ -f "/etc/systemd/system/${SERVICE_NAME}-cloudflared.service" ]; then
    systemctl disable --now "${SERVICE_NAME}-cloudflared.service" >/dev/null 2>&1 || true
  fi
}

wait_cloudflared_url() {
  service="${SERVICE_NAME}-cloudflared.service"
  i=0
  while [ "$i" -lt 40 ]; do
    url="$(journalctl -u "$service" -n 120 --no-pager 2>/dev/null | grep -oE 'https://[^ ]+\.trycloudflare\.com' | tail -1 || true)"
    if [ -n "$url" ]; then
      printf '%s' "$url"
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done
  return 1
}

install_binary() {
  mkdir -p "$INSTALL_DIR"
  tmp="$(mktemp)"
  if [ -n "$BINARY_URL" ]; then
    url="$BINARY_URL"
  else
    tag="$(latest_tag)" || die "cannot resolve latest x-tunnel release tag; set --version or --binary-url"
    arch="$(detect_arch)"
    url="https://github.com/${REPO}/releases/download/${tag}/x-tunnel_${tag}_linux_${arch}"
  fi
  log "downloading x-tunnel from $url"
  download "$url" "$tmp"
  install -m 0755 "$tmp" "${INSTALL_DIR}/x-tunnel"
  rm -f "$tmp"
}

print_summary() {
  forward="$1"
  cloud_url="$2"
  log ""
  log "x-tunnel server installed"
  log "  mode: $MODE"
  log "  service: ${SERVICE_NAME}.service"
  log "  binary: ${INSTALL_DIR}/x-tunnel"
  log "  config: ${CONFIG_DIR}/server.json"
  log "  listen: $SERVER_LISTEN"
  log "  metrics: $METRICS"
  if [ "$MODE" = "cloudflared" ]; then
    log "  cloudflared service: ${SERVICE_NAME}-cloudflared.service"
    log "  cloudflared url: $cloud_url"
  fi
  log "  client forward: $forward"
  log ""
  printf '%s\n' '--- client config ---'
  write_client_config "$forward" false
  printf '%s\n' '--- client config with websocket_front_proxy ---'
  write_client_config "$forward" true
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    --version) VERSION="$2"; shift 2 ;;
    --binary-url) BINARY_URL="$2"; shift 2 ;;
    --token) TOKEN="$2"; shift 2 ;;
    --listen-port) LISTEN_PORT="$2"; shift 2 ;;
    --listen-host) LISTEN_HOST="$2"; shift 2 ;;
    --path) TUNNEL_PATH="$2"; shift 2 ;;
    --metrics) METRICS="$2"; shift 2 ;;
    --public-host) PUBLIC_HOST="$2"; shift 2 ;;
    --upstream-socks5) UPSTREAM_SOCKS5="$2"; shift 2 ;;
    --cidr) CIDR="$2"; shift 2 ;;
    --allow-target) ALLOW_TARGET="$2"; shift 2 ;;
    --deny-target) DENY_TARGET="$2"; shift 2 ;;
    --allow-host) ALLOW_HOST="$2"; shift 2 ;;
    --deny-host) DENY_HOST="$2"; shift 2 ;;
    --max-clients) MAX_CLIENTS="$2"; shift 2 ;;
    --max-streams) MAX_STREAMS="$2"; shift 2 ;;
    --install-dir) INSTALL_DIR="$2"; shift 2 ;;
    --config-dir) CONFIG_DIR="$2"; shift 2 ;;
    --service-name) SERVICE_NAME="$2"; shift 2 ;;
    --client-listen) CLIENT_LISTEN="$2"; shift 2 ;;
    --client-connections) CLIENT_CONNECTIONS="$2"; shift 2 ;;
    --client-fallback) CLIENT_FALLBACK="$2"; shift 2 ;;
    --client-insecure) CLIENT_INSECURE="$2"; shift 2 ;;
    --client-metrics) CLIENT_METRICS="$2"; shift 2 ;;
    --skip-start) SKIP_START=true; shift ;;
    --print-only) PRINT_ONLY=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

interactive_prompts

case "$MODE" in
  cloudflared|direct) ;;
  *) die "--mode must be cloudflared or direct" ;;
esac

case "$TUNNEL_PATH" in
  /*) ;;
  *) TUNNEL_PATH="/$TUNNEL_PATH" ;;
esac

if [ -z "$TOKEN" ]; then
  TOKEN="$(random_token)"
fi

if [ "$MODE" = "cloudflared" ]; then
  [ -n "$LISTEN_HOST" ] || LISTEN_HOST="127.0.0.1"
else
  [ -n "$LISTEN_HOST" ] || LISTEN_HOST="0.0.0.0"
  if [ -z "$PUBLIC_HOST" ]; then
    PUBLIC_HOST="$(detect_public_host 2>/dev/null || true)"
  fi
  prompt PUBLIC_HOST "Direct-mode public host/IP" "$PUBLIC_HOST"
  [ -n "$PUBLIC_HOST" ] || die "direct mode requires --public-host when public IP detection fails"
fi

SERVER_LISTEN="ws://${LISTEN_HOST}:${LISTEN_PORT}${TUNNEL_PATH}"

if [ "$MODE" = "direct" ]; then
  CLIENT_FORWARD="ws://${PUBLIC_HOST}:${LISTEN_PORT}${TUNNEL_PATH}"
else
  CLIENT_FORWARD="wss://pending-cloudflared-url${TUNNEL_PATH}"
fi

if is_true "$PRINT_ONLY"; then
  print_summary "$CLIENT_FORWARD" ""
  exit 0
fi

as_root
need_cmd systemctl
need_cmd awk
need_cmd grep
need_cmd sed

mkdir -p "$CONFIG_DIR"
install_binary
write_server_config "${CONFIG_DIR}/server.json" "$SERVER_LISTEN"
write_systemd_service

if [ "$MODE" = "cloudflared" ]; then
  install_cloudflared
  write_cloudflared_service
fi

if ! is_true "$SKIP_START"; then
  start_services
fi

cloud_url=""
if [ "$MODE" = "cloudflared" ]; then
  if is_true "$SKIP_START"; then
    cloud_url="not-started"
  else
    cloud_url="$(wait_cloudflared_url)" || die "cloudflared did not publish a trycloudflare.com URL; inspect: journalctl -u ${SERVICE_NAME}-cloudflared.service"
  fi
  CLIENT_FORWARD="${cloud_url}${TUNNEL_PATH}"
  CLIENT_FORWARD="wss://${CLIENT_FORWARD#https://}"
fi

"${INSTALL_DIR}/x-tunnel" -version >&2 || true
if ! is_true "$SKIP_START"; then
  systemctl is-active "${SERVICE_NAME}.service" >/dev/null || die "${SERVICE_NAME}.service is not active"
  if [ "$MODE" = "cloudflared" ]; then
    systemctl is-active "${SERVICE_NAME}-cloudflared.service" >/dev/null || die "${SERVICE_NAME}-cloudflared.service is not active"
  fi
fi

print_summary "$CLIENT_FORWARD" "$cloud_url"
